#! /bin/sh
#
##################################################################################
#
# Purpose: To remove /tmp/testSlurp*.bin which are generated by the autobuild
#          during a test process.
# Author: James M Nguyen
#
#################################################################################
#
export SCRIPT_DIR=`pwd`
export LOG_FILE=${SCRIPT_DIR}/$0.log

rm /tmp/testSlurp*.bin &> ${LOG_FILE}

unset LOG_FILE
unset SCRIPT_DIR

# End of script.

